---
spreadsheet_title: Behaviour metadata
spreadsheet_id: 1fMnVXrDeaWTkX-TT21F4mFuAlaXIe6uVteEjv8mH0Q4
parent_directory: /Volumes/MarcBusche/Josef/backup/data/behaviormetadataBackup
header_row: 1
---
spreadsheet_title: mouse metadata
spreadsheet_id: 1QVkoP9g2XUB8OBu4Hs4d2h3ebUQx2sAeQ4wMnlLhbv8
parent_directory: /Volumes/MarcBusche/Josef/backup/data/mousemetadataBackup
header_row: 1