---
spreadsheet_title:                                                  # Title of spreadsheet for identification
active:                                                             # Either 'True' or 'False'
spreadsheet_id:                                                     # https://docs.google.com/spreadsheets/d/SPREADSHEET_ID
parent_directory:                                                   # Umbrella folder for the worsheet .csv files
header_row:                                                         # Row number of row which contains the headers
all_worksheets:                                                     # Either 'True' or 'False'
worksheets:                                                         # If 'all_worksheets' = 'False', specify a list of worksheets to be saved
  -
---
spreadsheet_title:                                                  # Title of spreadsheet for identification
active:                                                             # Either 'True' or 'False'
spreadsheet_id:                                                     # https://docs.google.com/spreadsheets/d/SPREADSHEET_ID
parent_directory:                                                   # Umbrella folder for the worsheet .csv files
header_row:                                                         # Row number of row which contains the headers
all_worksheets:                                                     # Either 'True' or 'False'
worksheets:                                                         # If 'all_worksheets' = 'False', specify a list of worksheets to be saved
  -