---
sh_title: Behaviour metadata
parent_directory: /Volumes/MarcBusche/Josef/backup/data/behaviormetadataBackup
---
sh_title: mouse metadata
parent_directory: /Volumes/MarcBusche/Josef/backup/data/mousemetadataBackup